version: "3.9"
services:
    django:
        build: .
        command: sh -c "
            apk add sqlite &&
            python manage.py makemigrations &&
            python manage.py migrate && 
            cp ./InitialData/json.py /usr/local/lib/python3.9/site-packages/django/core/serializers &&
            python manage.py loaddata InitialData/comunes.json &&
            python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on: 
            - redis_server
    redis_server:
        image: redis:alpine3.14


